# Generated by Django 4.2.1 on 2023-05-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='crated',
            new_name='created',
        ),
    ]
